DIALOG DLG_SETTINGS {

    NAME DLG_SETTINGS_TITLE;

    GROUP {
      NAME CHANNELS_SELECTION_TITLE;
      BORDERSTYLE BORDER_OUT;
      BORDERSIZE 10, 10, 10, 10;
      SCALE_H; SCALE_V;
      COLUMNS 3;

      STATICTEXT { NAME ID_HEADER_EMPTY; }
      STATICTEXT { NAME ID_HEADER_LABEL_ACTIVE;  CENTER_H; }
      STATICTEXT { NAME ID_HEADER_LABEL_APPLY_COLOR; CENTER_H; }


      STATICTEXT { NAME ID_HEADER_EMPTY; SIZE 200, 0;}
      SEPARATOR { SCALE_H; SIZE 150, 0; }
      SEPARATOR { SCALE_H; SIZE 150, 0; }


      STATICTEXT { NAME ID_MATERIAL_CHANNEL_COLOR; SIZE 200, 0; }
      CHECKBOX ID_CHOICE_00 { CENTER_H; }
      CHECKBOX ID_CHOICE_01 { CENTER_H; }

      STATICTEXT { NAME ID_MATERIAL_CHANNEL_DIFFUSION; SCALE_H; }
      CHECKBOX ID_CHOICE_02 { CENTER_H; };
      CHECKBOX ID_CHOICE_03 { CENTER_H; };

      STATICTEXT { NAME ID_MATERIAL_CHANNEL_LUMINANCE; SCALE_H; }
      CHECKBOX ID_CHOICE_04 { CENTER_H; };
      CHECKBOX ID_CHOICE_05 { CENTER_H; };

      STATICTEXT { NAME ID_MATERIAL_CHANNEL_TRANSPARENCY; SCALE_H; }
      CHECKBOX ID_CHOICE_06 { CENTER_H; };
      CHECKBOX ID_CHOICE_07 { CENTER_H; };

      STATICTEXT { NAME ID_MATERIAL_CHANNEL_REFLECTANCE; SCALE_H; }
      CHECKBOX ID_CHOICE_08 { CENTER_H; };
      CHECKBOX ID_CHOICE_09 { CENTER_H; };

      STATICTEXT { NAME ID_MATERIAL_CHANNEL_ENVIRONMENT; SCALE_H; }
      CHECKBOX ID_CHOICE_10 { CENTER_H; };
      CHECKBOX ID_CHOICE_11 { CENTER_H; };

      STATICTEXT { NAME ID_MATERIAL_CHANNEL_FOG; SCALE_H; }
      CHECKBOX ID_CHOICE_12 { CENTER_H; };
      CHECKBOX ID_CHOICE_13 { CENTER_H; };

      STATICTEXT { NAME ID_MATERIAL_CHANNEL_BUMP; SCALE_H; }
      CHECKBOX ID_CHOICE_14 { CENTER_H; };
      CHECKBOX ID_CHOICE_15 { CENTER_H; };

      STATICTEXT { NAME ID_MATERIAL_CHANNEL_NORMAL; SCALE_H; }
      CHECKBOX ID_CHOICE_16 { CENTER_H; };
      CHECKBOX ID_CHOICE_17 { CENTER_H; };

      STATICTEXT { NAME ID_MATERIAL_CHANNEL_ALPHA; SCALE_H; }
      CHECKBOX ID_CHOICE_18 { CENTER_H; };
      CHECKBOX ID_CHOICE_19 { CENTER_H; };

      STATICTEXT { NAME ID_MATERIAL_CHANNEL_GLOW; SCALE_H; }
      CHECKBOX ID_CHOICE_20 { CENTER_H; };
      CHECKBOX ID_CHOICE_21 { CENTER_H; };

      STATICTEXT { NAME ID_MATERIAL_CHANNEL_DISPLACEMENT; SCALE_H; }
      CHECKBOX ID_CHOICE_22 { CENTER_H; };
      CHECKBOX ID_CHOICE_23 { CENTER_H; };
    }

    GROUP {
      COLUMNS 1;
      SPACE 5,5;
      BORDERSIZE 10, 10, 10, 10;
      CENTER_H; SCALE_V;

      BUTTON ID_BTN_SAVE { NAME ID_BTN_SAVE; SIZE 200, 20; }
    }

}
