enum
{

    DLG_SETTINGS = 1000,
    ID_BTN_SAVE = 2000,
    DLG_SETTINGS_TITLE,
    CHANNELS_SELECTION_TITLE,

    ID_HEADER_EMPTY,
    ID_HEADER_LABEL_ACTIVE,
    ID_HEADER_LABEL_APPLY_COLOR,

    ID_MATERIAL_CHANNEL_COLOR,
    ID_MATERIAL_CHANNEL_DIFFUSION,
    ID_MATERIAL_CHANNEL_LUMINANCE,
    ID_MATERIAL_CHANNEL_TRANSPARENCY,
    ID_MATERIAL_CHANNEL_REFLECTANCE,
    ID_MATERIAL_CHANNEL_ENVIRONMENT,
    ID_MATERIAL_CHANNEL_FOG,
    ID_MATERIAL_CHANNEL_BUMP,
    ID_MATERIAL_CHANNEL_NORMAL,
    ID_MATERIAL_CHANNEL_ALPHA,
    ID_MATERIAL_CHANNEL_GLOW,
    ID_MATERIAL_CHANNEL_DISPLACEMENT,

    ID_CHOICE_00 = 3000,
    ID_CHOICE_01,
    ID_CHOICE_02,
    ID_CHOICE_03,
    ID_CHOICE_04,
    ID_CHOICE_05,
    ID_CHOICE_06,
    ID_CHOICE_07,
    ID_CHOICE_08,
    ID_CHOICE_09,
    ID_CHOICE_10,
    ID_CHOICE_11,
    ID_CHOICE_12,
    ID_CHOICE_13,
    ID_CHOICE_14,
    ID_CHOICE_15,
    ID_CHOICE_16,
    ID_CHOICE_17,
    ID_CHOICE_18,
    ID_CHOICE_19,
    ID_CHOICE_20,
    ID_CHOICE_21,
    ID_CHOICE_22,
    ID_CHOICE_23,



    _DUMMY_ELEMENT_

};